name: CI Pdb

on:
  push:
    branches: 
        - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: setup pg
        working-directory: ./
        run: docker-compose -f ./tests/playwright/scripts/docker-compose-playwright-pg.yml up -d &
      - name: install dependencies nocodb-sdk
        working-directory: ./packages/nocodb-sdk
        run: npm install
      - name: build nocodb-sdk
        working-directory: ./packages/nocodb-sdk
        run: npm run build:main
      - name: Install dependencies
        working-directory: ./packages/nocodb
        run: npm install
      - name: run unit tests
        working-directory: ./packages/nocodb
        run: npm run test:unit:pg
